name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
    
      - name: Autenticação no Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
    
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./chart
          file: ./chart/Dockerfile
          push: true
          tags:
            lethiciahas/jack-challenge:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Deploy to k8s
        uses: paychantorg/action.k8s@v1.0.0
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: |
            helm list
            kubectl get nodes
      
      
      
    
      
