name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
    
      - name: Autenticação no Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
    
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./chart
          file: ./chart/Dockerfile
          push: true
          tags:
            lethiciahas/jack-challenge:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.3.0
               
      - name: Helm Deploy
        uses: github-action-helm3@v2
        with:
         exec: helm install wp-lethicia-andrade estag --create-namespace -n lethicia-andrade --set persistence.enabled=false --set ingress.enabled=true --set ingress.hostname="lethiciahas.stag.jac.bsb.br" --set resources.requests=null --set mariadb.primary.persistence.enabled=false 
         kubeconfig: ${{secrets.K8S_CONFIG}}
      
    
      
