name: CI-CD

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
    
      - name: Autenticação no Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
    
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./chart
          file: ./chart/Dockerfile
          push: true
          tags:
            lethiciahas/jack-challenge:latest
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Adicionando context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
               
      - name: Helm Deploy
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
         exec: helm upgrade --install wp-lethicia-andrade ./chart/lethiciahas-chart
         kubeconfig: ${{secrets.K8S_CONFIG}}
      
    
      
